language: objective-c
xcode_workspace: workspace.xcworkspace
xcode_scheme: test

script:
  - xcodebuild -workspace "workspace.xcworkspace" -scheme "test" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
