language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
xcode_workspace: workspace.xcworkspace
xcode_scheme: test

script:
  - xcodebuild -workspace "workspace.xcworkspace" -scheme "test" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace "workspace.xcworkspace" -scheme "test" -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
