language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
xcode_workspace: workspace.xcworkspace
xcode_scheme: test

script:
  - xcodebuild -workspace "workspace.xcworkspace" -scheme "test" clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
